### PR TITLE
Add TPS Spoofing.

### PR DESCRIPTION
**Pull request by RealTriassic**
This is gay tbh.

### CODE REVIEW

**Comment by ItsYaBoyBanana** [comment]
I LOVE YOU <333333

**Comment by ItsYaBoyBanana** [comment]
:DDDD now marry me please

**Comment by RealTriassic** [comment]
> :DDDD now marry me please

no srry

**Comment by ItsYaBoyBanana** [comment]
> > :DDDD now marry me please
> 
> no srry

why ;(

**Comment by ItsYaBoyBanana** [comment]
> > :DDDD now marry me please
> 
> no srry

why ;(

**Comment by LamakerOffical** [comment]
f#ck u all

**Comment by ItsYaBoyBanana** [comment]
> f#ck u all

:((((((((((((((

**Comment by Chicadaa** [comment]
uh how this is works

**Comment by ItsYaBoyBanana** [comment]
> uh how this is works

i don't know

**Comment by LiljaFi** [comment]
insane pr

**Pull request merged**
